### ISSUE TITLE
Album Detail Page

### ISSUE THREAD

**Issue by dustyterraform** [chrisrobbins/Vinylizr#4]
Clean up some of the data. More white space

**Comment by F10lab** [comment]
![screen shot 2017-05-18 at 7 30 53 pm](https://cloud.githubusercontent.com/assets/11743036/26230830/9103dcbe-3c00-11e7-94e7-fb3a9b643ad2.png)

**Comment by dustyterraform** [comment]
This looks killer @F10lab! What if we don't use the material design button style. Maybe flat? we aren't using any material design elements. Thoughts? Maybe the icon with an outline around it? Everything else looks solid homie.

**Comment by dustyterraform** [comment]
![04 01 - details landing](https://cloud.githubusercontent.com/assets/26827345/26288795/80baf7ce-3e5e-11e7-9fb7-0a32ff1c8617.png)

**Comment by dustyterraform** [comment]
simplified it by removing those buttons from within the overflow menu. thoughts? clicking on it again would remove it from your list but would our users know to do that?

**Comment by dustyterraform** [comment]
@F10lab this will help. they have the api objects listed on the left. https://developers.deezer.com/api

**Comment by F10lab** [comment]
This I love. Was always back & forth about that floating action button. Too much extra interaction.

**Comment by dustyterraform** [comment]
Clean up data
